spring:
  application:
    name: langchain4j-2

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${QWEN_API_KEY}
      model-name: qwen-plus
      log-responses: true
      log-requests: true
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${QWEN_API_KEY}
      model-name: qwen-plus
      log-responses: true
      log-requests: true
  community:
    dashscope:
      chat-model:
        api-key:  ${QWEN_API_KEY}
        model-name: qwen-plus
    redis:
      host: 1.94.101.207
      port: 6379
      password: PGFmy8pbBxeJYpYZ
      prefix: "langchain4j:arg:"
      user: default


logging:
  level:
    dev.langchain4j: debug
    root: info
