#-----------------数据库---------------------------------------
spring:
  application:
    name: basics
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learn?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 116.62.48.25
    port: 6378
    lettuce:
      pool:
        min-idle: 0
        max-wait: -1
        max-idle: 8
        max-active: 8
    password: 123456
#  kafka:
#    producer:
#      bootstrap-servers: 127.0.0.1:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: foo
  cache:
    type: redis
    cache-names: redisCache
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 60s
    listener:
      simple:
        acknowledge-mode: manual # 手动ack auto自动ack
        retry:
          enabled: true # 开启重试
          max-attempts: 3  # 最大重试次数
          max-interval: 1000ms # 最大间隔时间
        default-requeue-rejected: false # 被拒绝的消息是否重新入列 默认为true
    publisher-returns: true # 消息发布返回
    publisher-confirm-type: simple
  data:
    mongodb:
      uri: mongodb://admin:Rendui123456!@s-2ze3517db91ac0e4-pub.mongodb.rds.aliyuncs.com:3717,s-2ze1a4695cbb9c84-pub.mongodb.rds.aliyuncs.com:3717/rendui-test
    elasticsearch:
      client:
        reactive:
          endpoints: 139.196.200.244:9200
          username: elastic
          password: 123456
          connection-timeout: 10s
  elasticsearch:
    rest:
      uris: 139.196.200.244:9200
  mail:
    host: smtp.163.com
    password: FQXKPKXUTNZCKUEA
    username: fan18324485857@163.com


server:
  port: 9000

person:
  id: 100
  age: 10
  birthday: 1992/12/20
  map: {ss: 123,name: xingkong,age: sdf}
  list:
    - 123
    - dfxj
    - xingkong
  name: fan18324485857@163.com

rabbitmq:
  queue:
    name: ${server.port}

echarts:
  host: http://127.0.0.1:6666



#------------日志---------------------
logging:
  level:
    javax:
      activation: debug
    org:
      mybatis:
        spring: debug
      springframework: debug
      springframework.boot: debug
    root: debug
