#-----------------数据库---------------------------------------
spring:
  datasource:
    url: jdbc:mysql://114.55.170.179:3306/learn?characterEncoding=utf8
    username: root
    password: Jj123456!@#
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1


server:
  port: 9000

rabbitmq:
  queue:
    name: ${server.port}


#------------日志---------------------
logging:
  level:
    javax:
      activation: error
    org:
      mybatis:
        spring: debug
      springframework:
        boot: info
    root: debug
