#-----------------数据库---------------------------------------
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learn?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 116.62.48.25
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1
    port: 6378
    password: 123456
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: foo
  cache:
    type: redis
    cache-names: redisCache
  rabbitmq:
    host: 116.62.48.25
    port: 5662
    username: colovu
    password: pass4colovu
    connection-timeout: 60s
    listener:
      simple:
        acknowledge-mode: manual # 手动ack auto自动ack
        retry:
          enabled: true # 开启重试
          max-attempts: 3  # 最大重试次数
          max-interval: 1000ms # 最大间隔时间
        default-requeue-rejected: false # 被拒绝的消息是否重新入列 默认为true
    publisher-confirms: true # 消息发布确认
    publisher-returns: true # 消息发布返回
  data:
    mongodb:
      host: 116.62.48.25
      port: 27017
      database: jiwang-cmdb

server:
  port: 9000

person:
  id: 100
  age: 10
  birthday: 1992/12/20
  map: {ss: 123,name: xingkong,age: sdf}
  list:
    - 123
    - dfxj
    - xingkong
  name: fan18324485857@163.com

rabbitmq:
  queue:
    name: ${server.port}


#------------日志---------------------
logging:
  level:
    javax:
      activation: debug
    org:
      mybatis:
        spring: debug
      springframework: debug
      springframework.boot: debug
    root: debug
