#-----------------数据库---------------------------------------
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learn?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: foo
  cache:
    type: redis
    cache-names: redisCache

server:
  port: 9000

rabbitmq:
  queue:
    name: ${server.port}


#------------日志---------------------
logging:
  level:
    javax:
      activation: debug
    org:
      mybatis:
        spring: debug
      springframework: debug
      springframework.boot: debug
    root: debug
